// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7yZlcvm8sZY0Of7hD0bfAqJ3nKVJ8ET8',
    appId: '1:566805816062:web:a90e2d01a4d980507f7baf',
    messagingSenderId: '566805816062',
    projectId: 'quiz-maker-746b7',
    authDomain: 'quiz-maker-746b7.firebaseapp.com',
    storageBucket: 'quiz-maker-746b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDadLEpTYKigAaXiOzNgY4211kLMCjwBKE',
    appId: '1:566805816062:android:eb9fc7dc4b33d2c07f7baf',
    messagingSenderId: '566805816062',
    projectId: 'quiz-maker-746b7',
    storageBucket: 'quiz-maker-746b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3YmMGCUuk_PDaZp_upINjfWPAV5ulDqM',
    appId: '1:566805816062:ios:bd55828368199e747f7baf',
    messagingSenderId: '566805816062',
    projectId: 'quiz-maker-746b7',
    storageBucket: 'quiz-maker-746b7.appspot.com',
    iosClientId: '566805816062-rk2c2ukmcv9inacg5rg6980fohfm12td.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizMaker',
  );
}
